// ============================================================
//  AŞK KARNESİ — SORU BANKASI
//  d: ders id · l: seviye (1 Tatlı, 2 Cesur, 3 Acımasız)
//  a: radar ekseni · p: "Evet" cevabı ekseni yükseltir mi
//  Eksenler: emek, sadakat, romantizm, sabir, cesaret, uyum
// ============================================================

export const DERSLER = [
  { id: 1, ad: 'Sadakat 101', emoji: '🛡️' },
  { id: 2, ad: 'Kıskançlık Yönetimi', emoji: '👀' },
  { id: 3, ad: 'Fedakârlık Uygulamaları', emoji: '💪' },
  { id: 4, ad: 'İletişim Sanatı', emoji: '🗣️' },
  { id: 5, ad: 'Romantizm Atölyesi', emoji: '🌹' },
  { id: 6, ad: 'Gündelik Hayat Bilgisi', emoji: '🏠' },
  { id: 7, ad: 'Para ve Ekonomi', emoji: '💸' },
  { id: 8, ad: 'Aile İlişkileri', emoji: '👪' },
  { id: 9, ad: 'Gelecek Planlama', emoji: '🔮' },
  { id: 10, ad: 'Geçmiş Tarihi', emoji: '📜' },
  { id: 11, ad: 'Yasak Bölge', emoji: '🔞', adult: true },
]

export const AXES = [
  { key: 'emek', ad: 'Emek' },
  { key: 'sadakat', ad: 'Sadakat' },
  { key: 'romantizm', ad: 'Romantizm' },
  { key: 'sabir', ad: 'Sabır' },
  { key: 'cesaret', ad: 'Cesaret' },
  { key: 'uyum', ad: 'Uyum' },
]

// Not: sorular ikinci tekil şahısa sorulur; her iki taraf da kendi adına cevaplar.
export const QUESTIONS = [
  // ---------- 1 · SADAKAT 101 ----------
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Partnerine karşı kendini yüzde yüz dürüst hissediyor musun?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Telefonunu partnerine kilitsiz teslim edebilir misin?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Partnerin yanında yokken de onu savunur musun?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Uzak mesafe olsa bu ilişki yine de yürür müydü sence?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Partnerinin sana tamamen güvendiğini düşünüyor musun?' },
  { d: 1, l: 1, a: 'cesaret', p: true, t: 'Sosyal medyada kimleri takip ettiğini partnerin bilse rahatsız olur muydun? (Hayır=rahatım)' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Bir sırrını partnerine emanet edebilir misin?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Partnerin en yakın arkadaşınla yalnız kahve içse sorun olmaz mı?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'İlişkinizde kıskançlıktan çok güven mi hakim?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Partnerinin verdiği sözleri tuttuğuna inanıyor musun?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Bu ilişkiyi çevrene gururla anlatıyor musun?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Partnerin bir sözünü unutsa kasıt aramadan geçer misin?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'İkinizin de flört sınırlarını aynı çizdiğinizi düşünüyor musun?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Partnerin sana bir şey söylediğinde kanıt istemeden inanır mısın?' },
  { d: 1, l: 1, a: 'sadakat', p: true, t: 'Gece geç saatte kiminle yazıştığını sorsa açık açık söyler misin?' },
  { d: 1, l: 2, a: 'cesaret', p: true, t: 'Partnerinin telefonuna bakmayı hiç aklından geçirdin mi?' },
  { d: 1, l: 2, a: 'sadakat', p: false, t: 'Eski sevgilinden mesaj gelse partnerine söylemeden siler miydin?' },
  { d: 1, l: 2, a: 'sadakat', p: true, t: 'Biri sana yürüse partnerine anında haber verir misin?' },
  { d: 1, l: 2, a: 'cesaret', p: true, t: 'Partnerin sormasa da hoşlanılan biri tarafından iltifat aldığını söyler misin?' },
  { d: 1, l: 2, a: 'sadakat', p: false, t: 'Sırf tartışma çıkmasın diye küçük yalanlar söylediğin oluyor mu?' },
  { d: 1, l: 2, a: 'sadakat', p: true, t: 'Partnerin bir haftalığına telefonunu kapatsa güvenin sarsılmaz mı?' },
  { d: 1, l: 2, a: 'sadakat', p: false, t: 'Bekar arkadaş ortamında partnerinden bahsetmeden takıldığın oluyor mu?' },
  { d: 1, l: 2, a: 'cesaret', p: true, t: 'İlişkide bir şeyleri sakladığın dönem oldu mu? (Cesursan Evet de)' },
  { d: 1, l: 2, a: 'sadakat', p: true, t: 'Partnerinin eski sevgilisiyle aynı ortamda sakin kalabilir misin?' },
  { d: 1, l: 2, a: 'sadakat', p: true, t: 'Sana çok çekici gelen biriyle uzun süre yalnız kalsan sınırlar net mi?' },
  { d: 1, l: 2, a: 'sadakat', p: false, t: 'Instagram keşfetinde birine fazla uzun baktığın için kendini suçlu hissettin mi?' },
  { d: 1, l: 2, a: 'sadakat', p: true, t: 'Partnerin şifreni istese vermekte tereddüt etmez misin?' },
  { d: 1, l: 2, a: 'sadakat', p: true, t: 'Flört ile samimiyet arasındaki çizgiyi partnerinle aynı yerde mi çiziyorsunuz sence?' },
  { d: 1, l: 2, a: 'cesaret', p: true, t: 'Partnerine söylemediğin bir DM hikayen var mı? (Cesursan Evet)' },
  { d: 1, l: 2, a: 'sadakat', p: true, t: 'İlişki yokken bile flörtleştiğin kişiye net davranır mıydın?' },
  { d: 1, l: 3, a: 'sadakat', p: false, t: 'Kimse asla öğrenmeyecek olsa partnerini aldatır mıydın?' },
  { d: 1, l: 3, a: 'sadakat', p: true, t: 'Partnerin seni duygusal olarak aldatsa (mesajlaşma düzeyinde) affeder miydin?' },
  { d: 1, l: 3, a: 'cesaret', p: true, t: 'Bu ilişkide partnerinin bilmediği bir gerçek var mı? (Cesursan Evet)' },
  { d: 1, l: 3, a: 'sadakat', p: false, t: 'Hayranlık duyduğun biri sana açılsa bir an bile tereddüt eder miydin?' },
  { d: 1, l: 3, a: 'sadakat', p: true, t: 'Partnerin geçmişte seni ufak da olsa kıskançlıktan test etti mi sence?' },
  { d: 1, l: 3, a: 'sadakat', p: false, t: 'İlişkiniz boyunca “keşke bekar olsam” dediğin bir gece oldu mu?' },
  { d: 1, l: 3, a: 'sadakat', p: true, t: 'Aldatmanın tek seferlik hali affedilebilir mi sence?' },
  { d: 1, l: 3, a: 'cesaret', p: true, t: 'Partnerinin telefonuna gizlice baktın mı hiç? (Cesursan Evet)' },
  { d: 1, l: 3, a: 'sadakat', p: false, t: 'Eski sevgilinle “sadece arkadaşız” diye görüşmeye devam eder miydin?' },
  { d: 1, l: 3, a: 'sadakat', p: true, t: 'Partnerin sana geçmiş flörtlerinin tam listesini verse okumadan kapatır mıydın?' },
  { d: 1, l: 3, a: 'sadakat', p: false, t: 'Bu ilişki bitse bir hafta içinde birine yazacağın biri var mı?' },
  { d: 1, l: 3, a: 'sadakat', p: true, t: 'Sence partnerin, senin onu sevdiğinden daha çok mu seviyor seni?' },
  { d: 1, l: 3, a: 'cesaret', p: true, t: 'Partnerinin en yakın arkadaşını bir an için çekici buldun mu? (Cesursan Evet)' },
  { d: 1, l: 3, a: 'sadakat', p: false, t: 'Sadakat sence biraz da fırsat bulamamak mıdır?' },
  { d: 1, l: 3, a: 'sadakat', p: true, t: 'İlişkiniz için “asla aldatmam” diye yemin edebilir misin?' },

  // ---------- 2 · KISKANÇLIK YÖNETİMİ ----------
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Partnerin karşı cinsten biriyle gülüşse sakin kalır mısın?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Kıskançlığını çoğu zaman kontrol edebildiğini düşünüyor musun?' },
  { d: 2, l: 1, a: 'cesaret', p: true, t: 'Kıskandığını partnerine açıkça söyleyebiliyor musun?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Partnerinin arkadaş ortamına karışmamayı başarabiliyor musun?' },
  { d: 2, l: 1, a: 'uyum', p: true, t: 'Tatlı kıskançlığın ilişkiye renk kattığını düşünüyor musun?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Partnerin bir gece arkadaşlarıyla çıksa rahat uyur musun?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Story beğenilerini dert etmeyen biri misin?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Partnerinin iş arkadaşlarıyla yemeğe çıkması seni germez mi?' },
  { d: 2, l: 1, a: 'cesaret', p: true, t: 'Kıskanç bir insan olduğunu kabul ediyor musun?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Partnerin spor salonuna gitse aklın hiç karışmaz mı?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Kıskançlık krizini bir saat içinde tatlıya bağlayabilir misin?' },
  { d: 2, l: 1, a: 'uyum', p: true, t: 'Partnerinin seni biraz kıskanması hoşuna gider mi?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Eski konuları kıskançlıkla yeniden açmamayı başarır mısın?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Partnerinin sana anlatmadığı bir arkadaş sohbeti olması normal mi sence?' },
  { d: 2, l: 1, a: 'sabir', p: true, t: 'Telefon gelince “kim o?” diye sormadan durabilir misin?' },
  { d: 2, l: 2, a: 'sabir', p: false, t: 'Partnerinin story izleyenlerini kontrol ettiğin oluyor mu?' },
  { d: 2, l: 2, a: 'sabir', p: false, t: 'Partnerinin eski sevgilisinin profiline girdiğin oldu mu?' },
  { d: 2, l: 2, a: 'sabir', p: true, t: 'Partnerin eski sevgilisiyle aynı işte çalışsa dayanabilir misin?' },
  { d: 2, l: 2, a: 'cesaret', p: true, t: 'Kıskançlıktan attığın bir mesajı sonradan sildiğin oldu mu? (Cesursan Evet)' },
  { d: 2, l: 2, a: 'sabir', p: false, t: 'Partnerinin çevrimiçi olma saatlerini takip ettiğin oluyor mu?' },
  { d: 2, l: 2, a: 'sabir', p: true, t: 'Partnerin karşı cinsten en yakın arkadaşıyla tatile gitse izin verir miydin?' },
  { d: 2, l: 2, a: 'sabir', p: false, t: 'Kıskançlık yüzünden bir geceyi mahvettiğin oldu mu?' },
  { d: 2, l: 2, a: 'sabir', p: true, t: 'Partnerinin telefonunda karşı cinsten kişilerin numarası olması sorun değil mi?' },
  { d: 2, l: 2, a: 'sabir', p: false, t: 'Partnerin biriyle fazla samimi konuştu diye içinden hesap sorduğun oldu mu?' },
  { d: 2, l: 2, a: 'cesaret', p: true, t: 'Kıskançlığın bazen kontrolden çıktığını itiraf eder misin?' },
  { d: 2, l: 2, a: 'sabir', p: true, t: 'Partnerinin “sadece arkadaşım” dediği kişiye güvenir misin?' },
  { d: 2, l: 2, a: 'sabir', p: false, t: 'Sevgilinin beğendiği fotoğrafları tek tek incelediğin oluyor mu?' },
  { d: 2, l: 2, a: 'sabir', p: true, t: 'Partnerin bir düğünde başkasıyla dans etse gülümseyerek izler misin?' },
  { d: 2, l: 2, a: 'sabir', p: false, t: 'Kıskançlıktan partnerine soğuk davrandığın olur mu?' },
  { d: 2, l: 2, a: 'sabir', p: true, t: 'Partnerinin sana söylemeden plan yapması seni krize sokmaz mı?' },
  { d: 2, l: 3, a: 'sabir', p: false, t: 'Partnerinin konumunu gizlice kontrol etmek ister miydin imkanın olsa?' },
  { d: 2, l: 3, a: 'cesaret', p: true, t: 'Partnerinin telefonunu eline geçirsen ilk mesajlara mı bakardın? (Cesursan Evet)' },
  { d: 2, l: 3, a: 'sabir', p: false, t: 'Kıskançlıktan bir ilişkiyi bitirme noktasına geldin mi hiç?' },
  { d: 2, l: 3, a: 'sabir', p: true, t: 'Partnerin eski sevgilisini “güzeldi/yakışıklıydı” dese sakince onaylar mısın?' },
  { d: 2, l: 3, a: 'sabir', p: false, t: 'Partnerinin geçmişindeki birine hâlâ diş biliyor musun?' },
  { d: 2, l: 3, a: 'sabir', p: true, t: 'Partnerin sana biriyle “sadece öğle yemeği” yediğini sonradan söylese sorun etmez misin?' },
  { d: 2, l: 3, a: 'cesaret', p: true, t: 'Partnerini gizlice test ettiğin bir an oldu mu? (Cesursan Evet)' },
  { d: 2, l: 3, a: 'sabir', p: false, t: 'Sence kıskançlık aşkın ölçüsü müdür?' },
  { d: 2, l: 3, a: 'sabir', p: true, t: 'Partnerinin sana çekici gelen bir arkadaşı olduğunu söylemesi dürüstlük müdür sence?' },
  { d: 2, l: 3, a: 'sabir', p: false, t: 'Partnerinin geçmiş ilişki sayısı seni rahatsız ediyor mu?' },
  { d: 2, l: 3, a: 'sabir', p: true, t: 'İlişkide özgürlük mü güvenlik mi dersen özgürlüğü mü seçersin?' },
  { d: 2, l: 3, a: 'sabir', p: false, t: 'Partnerin bir gün “bana alan lazım” dese panik yapar mısın?' },
  { d: 2, l: 3, a: 'cesaret', p: true, t: 'Kıskançlık yüzünden yaptığın en saçma şeyi partnerine anlatabilir misin?' },
  { d: 2, l: 3, a: 'sabir', p: false, t: 'Partnerinin başarısını bile bazen kıskandığın oluyor mu?' },
  { d: 2, l: 3, a: 'sabir', p: true, t: 'Partnerin ünlü biriyle fotoğraf çektirse ve o kişi flörtöz dursa gülüp geçer misin?' },

  // ---------- 3 · FEDAKÂRLIK UYGULAMALARI ----------
  { d: 3, l: 1, a: 'emek', p: true, t: 'Partnerin hasta olsa gece yarısı eczane turuna çıkar mısın?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Sevmediğin bir filmi sırf partnerin istiyor diye keyifle izler misin?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Partnerinin sevdiği yemeği öğrenip yapmayı denedin mi?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Yorgun olsan da partnerinin anlatacağı şeyi sonuna kadar dinler misin?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Özel günleri hatırlamak için çaba gösteriyor musun?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Partnerin üzgünken kendi planını iptal ettiğin olur mu?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Sürpriz hazırlamayı seven biri misin?' },
  { d: 3, l: 1, a: 'uyum', p: true, t: 'Partnerinin hobisine hiç sevmesen de eşlik eder misin?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Bu ilişki için konfor alanından çıktığını düşünüyor musun?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Partnerinin ailesinin davetine yorgunken bile gider misin?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Son bir ayda partnerin için “zahmetli” bir şey yaptın mı?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Partnerinin uykusu için sesini kısıp karanlıkta telefon oynadığın olur mu?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Kavga sonrası ilk adımı çoğunlukla sen mi atarsın?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Partnerinin sevdiği şarkıları öğrendiğin oluyor mu?' },
  { d: 3, l: 1, a: 'emek', p: true, t: 'Soğuk havada montunu partnerine verir misin?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Partnerin için yaşadığın şehri değiştirir miydin?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Kariyer fırsatı ile ilişki çakışsa ilişkiyi öncelemeyi düşünür müsün?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Partnerinin borcunu birikiminle kapatır mıydın?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'En sevdiğin alışkanlığını partnerin rahatsız oluyor diye bırakır mıydın?' },
  { d: 3, l: 2, a: 'cesaret', p: true, t: 'Bu ilişkide senin daha çok emek verdiğini düşünüyor musun? (Dürüst ol)' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Partnerinin kariyeri için kendi planını bir yıl erteler miydin?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Tatil tercihinde her sene ona uymayı kabul eder miydin?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Partnerin istese sosyal medyayı bırakır mıydın?' },
  { d: 3, l: 2, a: 'uyum', p: true, t: 'Arkadaş grubunla partnerin anlaşamasa dengede tutmayı becerir misin?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Partnerinin zor gününde işten izin alıp yanına gider miydin?' },
  { d: 3, l: 2, a: 'emek', p: false, t: 'Fedakârlıklarını partnerine sonradan fatura ettiğin olur mu?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Sabah uykusundan feragat edip partnerini havaalanına bırakır mısın?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'Partnerin diyetteyken ona destek olmak için tatlıyı sen de bırakır mısın?' },
  { d: 3, l: 2, a: 'emek', p: true, t: 'İlişki için terapiye gitmeyi kabul eder miydin?' },
  { d: 3, l: 2, a: 'cesaret', p: true, t: 'Partnerinin senin için yaptığı en büyük fedakârlığı sayabilir misin şu an?' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'Partnerin için hayalindeki işi reddeder miydin?' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'Gerekirse partnerin için ülke değiştirip sıfırdan başlar mıydın?' },
  { d: 3, l: 3, a: 'emek', p: false, t: 'Bu ilişkide fedakârlık terazisinin senden yana bozuk olduğunu düşünüyor musun?' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'Partnerin ağır hastalansa yıllarca bakımını üstlenir miydin?' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'Ailen bu ilişkiye karşı çıksa partnerini seçer miydin?' },
  { d: 3, l: 3, a: 'emek', p: false, t: 'Verdiğin emeğin karşılığını alamadığını hissettiğin oluyor mu?' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'Partnerinin rüyası için kendi birikimini riske atar mıydın?' },
  { d: 3, l: 3, a: 'cesaret', p: true, t: 'Bu ilişkiye verdiğin emeği 0-100 arası puanlasan 70 üstü çıkar mı? (Bar ile göster)' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'Çocuk kararında partnerinin istediği yöne razı olur muydun?' },
  { d: 3, l: 3, a: 'emek', p: false, t: 'Sence partnerin senin için aynı fedakârlıkları yapar mıydı? (Hayır=şüpheliyim)' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'İlişki krize girse pes etmeden aylarca uğraşır mıydın?' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'Partnerinin ailesine uzun süre bakmak gerekse üstlenir miydin?' },
  { d: 3, l: 3, a: 'emek', p: false, t: 'Fedakârlıkların bazen görünmez olduğunu düşünüyor musun?' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'Hayatını kurtarmak için organını partnerine verir miydin?' },
  { d: 3, l: 3, a: 'emek', p: true, t: 'İlişki için gururunu tamamen bir kenara koyduğun bir an oldu mu?' },

  // ---------- 4 · İLETİŞİM SANATI ----------
  { d: 4, l: 1, a: 'cesaret', p: true, t: 'Duygularını partnerine kolayca ifade edebiliyor musun?' },
  { d: 4, l: 1, a: 'uyum', p: true, t: 'Tartışmalarınız çoğunlukla çözümle mi bitiyor?' },
  { d: 4, l: 1, a: 'cesaret', p: true, t: 'Partnerine “bugün beni üzdün” diyebilir misin aynı gün içinde?' },
  { d: 4, l: 1, a: 'sabir', p: true, t: 'Partnerin konuşurken sözünü kesmeden dinleyebiliyor musun?' },
  { d: 4, l: 1, a: 'uyum', p: true, t: 'Kavga ederken bile saygı çizgisini koruduğunuzu düşünüyor musun?' },
  { d: 4, l: 1, a: 'cesaret', p: true, t: 'Özür dilemekte zorlanmayan biri misin?' },
  { d: 4, l: 1, a: 'uyum', p: true, t: 'Partnerinle her konuda konuşabildiğini hissediyor musun?' },
  { d: 4, l: 1, a: 'sabir', p: true, t: 'Partnerin sessizleştiğinde üstüne gitmeden bekleyebilir misin?' },
  { d: 4, l: 1, a: 'cesaret', p: true, t: 'Sevgini kelimelerle söylemeyi ihmal etmiyor musun?' },
  { d: 4, l: 1, a: 'uyum', p: true, t: 'Şakalarınızın dozunu iyi ayarladığınızı düşünüyor musun?' },
  { d: 4, l: 1, a: 'sabir', p: true, t: 'Partnerin aynı hikayeyi üçüncü kez anlatsa ilk kez gibi dinler misin?' },
  { d: 4, l: 1, a: 'cesaret', p: true, t: 'İhtiyacın olduğunda yardım istemeyi biliyor musun?' },
  { d: 4, l: 1, a: 'uyum', p: true, t: 'Mesajlaşma temponuz ikinize de uyuyor mu?' },
  { d: 4, l: 1, a: 'sabir', p: true, t: 'Kızgınken mesaj yazmak yerine sakinleşmeyi bekleyebilir misin?' },
  { d: 4, l: 1, a: 'cesaret', p: true, t: 'Partnerine en son ne zaman iltifat ettiğini hatırlıyor musun?' },
  { d: 4, l: 2, a: 'cesaret', p: false, t: 'Küstüğünde susma taktiği uyguladığın olur mu?' },
  { d: 4, l: 2, a: 'sabir', p: false, t: 'Tartışırken eski defterleri açtığın olur mu?' },
  { d: 4, l: 2, a: 'cesaret', p: true, t: 'Partnerinin bir davranışı seni utandırsa yüzüne söyler misin?' },
  { d: 4, l: 2, a: 'uyum', p: false, t: 'Tartışmayı kazanmak için karşı tarafı köşeye sıkıştırdığın olur mu?' },
  { d: 4, l: 2, a: 'cesaret', p: true, t: 'İlişkideki en büyük korkunu partnerine anlattın mı?' },
  { d: 4, l: 2, a: 'sabir', p: false, t: 'Kavgada sesini yükselttiğin oluyor mu?' },
  { d: 4, l: 2, a: 'cesaret', p: true, t: 'Partnerin seni eleştirdiğinde savunmaya geçmeden dinleyebilir misin?' },
  { d: 4, l: 2, a: 'uyum', p: false, t: 'Küslüğü bir günden uzun sürdürdüğün oldu mu?' },
  { d: 4, l: 2, a: 'cesaret', p: true, t: 'Ağladığını partnerine göstermekten çekinmez misin?' },
  { d: 4, l: 2, a: 'sabir', p: false, t: 'Tartışırken “her zaman şöylesin” gibi genellemeler yaptığın olur mu?' },
  { d: 4, l: 2, a: 'cesaret', p: true, t: 'Partnerinin ailesinden rahatsız olduğun bir şeyi ona söyleyebilir misin?' },
  { d: 4, l: 2, a: 'uyum', p: true, t: 'İkinizin de haklı olduğu kavgalarda ortayı bulmayı bilir misin?' },
  { d: 4, l: 2, a: 'cesaret', p: false, t: 'Sorunları konuşmak yerine zamana bıraktığın oluyor mu?' },
  { d: 4, l: 2, a: 'sabir', p: false, t: 'Kavga anında telefona sarılıp konuyu kapattığın olur mu?' },
  { d: 4, l: 2, a: 'cesaret', p: true, t: 'Partnerine söylemeye çekindiğin bir isteğin var mı? (Cesursan Evet)' },
  { d: 4, l: 3, a: 'cesaret', p: true, t: 'Partnerinin sende en sevmediğin huyunu yüzüne söyleyebilir misin şimdi?' },
  { d: 4, l: 3, a: 'cesaret', p: false, t: 'Kavgada bile bile kalbini kıracak cümle kurduğun oldu mu?' },
  { d: 4, l: 3, a: 'cesaret', p: true, t: 'İlişkiyi bitirmeyi düşündüğün bir dönemi partnerine itiraf eder misin?' },
  { d: 4, l: 3, a: 'sabir', p: false, t: 'Tartışmada üstünlük için partnerinin zayıf noktasını kullandığın oldu mu?' },
  { d: 4, l: 3, a: 'cesaret', p: true, t: '“Seni seviyorum” demediğin ama demen gereken bir an oldu mu? (Cesursan Evet)' },
  { d: 4, l: 3, a: 'uyum', p: false, t: 'Partnerini başkalarının yanında düzelttiğin/utandırdığın olur mu?' },
  { d: 4, l: 3, a: 'cesaret', p: true, t: 'İlişkideki bir sorunu ilk kez bu test sırasında fark ettin mi?' },
  { d: 4, l: 3, a: 'sabir', p: false, t: 'Kavgada kapıyı çarpıp gittiğin oldu mu?' },
  { d: 4, l: 3, a: 'cesaret', p: true, t: 'Partnerin şu an aklından geçeni sorsa filtresiz söyler miydin?' },
  { d: 4, l: 3, a: 'uyum', p: false, t: 'Bazı konuların bu ilişkide asla konuşulamadığını düşünüyor musun?' },
  { d: 4, l: 3, a: 'cesaret', p: true, t: 'Terapistin önünde her şeyi anlatmaya hazır mısın?' },
  { d: 4, l: 3, a: 'sabir', p: false, t: 'Sessiz kalarak partnerini cezalandırdığın oluyor mu?' },
  { d: 4, l: 3, a: 'cesaret', p: true, t: 'Partnerinin sana söylediği en ağır sözü hatırlıyor musun?' },
  { d: 4, l: 3, a: 'uyum', p: false, t: 'Tartışmalarınızın hep aynı konuya döndüğünü düşünüyor musun?' },
  { d: 4, l: 3, a: 'cesaret', p: true, t: 'Bu testin sonuçlarını saatlerce konuşmaya hazır mısın?' },

  // ---------- 5 · ROMANTİZM ATÖLYESİ ----------
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'El ele tutuşmadan yürüyemeyen çiftlerden misiniz?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Partnerine sebepsiz hediye aldığın olur mu?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Sarılmadan uyuyamayan taraf sen misin?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Tanışma hikayenizi anlatmayı hâlâ seviyor musun?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Partnerine günde en az bir kez güzel bir söz söyler misin?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Yıldönümü fikirleri üretmekte iyi misin?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Şarkı dinlerken partnerin aklına geliyor mu?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Uzun bakışmalarınız hâlâ oluyor mu?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Partnerinle fotoğraf çekilmeyi seviyor musun?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'İlk buluşmanızdaki heyecanı hâlâ hatırlıyor musun?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Partnerin için el yazısı not bıraktığın oldu mu?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Yağmurda yürümek romantik mi sence? (Islanmak dahil)' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Partnerinin gözlerinin rengini karanlıkta tarif edebilir misin?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Ona bakarken hâlâ için titriyor mu?' },
  { d: 5, l: 1, a: 'romantizm', p: true, t: 'Çift kombini yapmaya var mısın?' },
  { d: 5, l: 2, a: 'romantizm', p: false, t: 'Romantizmin zamanla azaldığını düşünüyor musun?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'Partnerin için şiir yazar mıydın (kötü de olsa)?' },
  { d: 5, l: 2, a: 'cesaret', p: true, t: 'Toplum içinde partnerine sarılmaktan çekinmez misin?' },
  { d: 5, l: 2, a: 'romantizm', p: false, t: 'Özel günleri unuttuğun oldu mu?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'Sürpriz tatil organize etmeyi becerebilir misin?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'Partnerinin en sevdiği çiçeği/tatlıyı biliyor musun?' },
  { d: 5, l: 2, a: 'romantizm', p: false, t: 'Romantik jestleri biraz “gereksiz” bulduğun oluyor mu?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'Kalabalık bir yerde partnerine aşkını ilan edebilir misin?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'Partnerinle ilgili bir anıyı anlatırken duygulandığın olur mu?' },
  { d: 5, l: 2, a: 'romantizm', p: false, t: 'Sevgi dilinizin uyuşmadığını hissettiğin anlar var mı?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'İlk öpücüğünüzün yerini ve gününü hatırlıyor musun?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'Partnerin için utanma riskine rağmen halka açık dans eder misin?' },
  { d: 5, l: 2, a: 'romantizm', p: false, t: 'Film romantizmi ile gerçek hayat arasında hayal kırıklığı yaşıyor musun?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'Partnerinin telefonundaki fotoğrafına bakıp gülümsediğin oluyor mu?' },
  { d: 5, l: 2, a: 'romantizm', p: true, t: 'Ona duyduğun ilk heyecanı geri getirebileceğine inanıyor musun?' },
  { d: 5, l: 3, a: 'romantizm', p: false, t: 'Romantizmi çoğunlukla partnerinin beklediği için mi yapıyorsun?' },
  { d: 5, l: 3, a: 'cesaret', p: true, t: 'Partnerine hiç “senden sıkıldım” hissi yaşadığını itiraf edebilir misin?' },
  { d: 5, l: 3, a: 'romantizm', p: true, t: 'Aşkın heyecan kısmı bitse bile kalır mıydın?' },
  { d: 5, l: 3, a: 'romantizm', p: false, t: 'Başka çiftlerin romantizmini görüp içinin burkulduğu oluyor mu?' },
  { d: 5, l: 3, a: 'romantizm', p: true, t: 'Partnerin sana olan aşkını 0-100 puanlasa 90 üstü verir mi sence?' },
  { d: 5, l: 3, a: 'cesaret', p: true, t: 'İlişkinizde aşkın mı alışkanlığın mı ağır bastığını söyleyebilir misin dürüstçe? (Aşk=Evet)' },
  { d: 5, l: 3, a: 'romantizm', p: true, t: 'Yeniden tanışsanız partnerine yine aşık olur muydun?' },
  { d: 5, l: 3, a: 'romantizm', p: false, t: 'Sevgini göstermekte partnerinden geride kaldığını düşünüyor musun?' },
  { d: 5, l: 3, a: 'romantizm', p: true, t: 'Partnerin “beni hâlâ ilk günkü gibi seviyor musun” dese gözünü kırpmadan Evet der misin?' },
  { d: 5, l: 3, a: 'romantizm', p: true, t: 'Aşk mektubu yazsan üç sayfayı doldurabilir misin?' },
  { d: 5, l: 3, a: 'romantizm', p: false, t: 'Romantik anlarda bile aklının başka yerde olduğu oluyor mu?' },
  { d: 5, l: 3, a: 'romantizm', p: true, t: 'Partnerinin en güzel yanını bir yabancıya bir dakika boyunca anlatabilir misin?' },
  { d: 5, l: 3, a: 'cesaret', p: true, t: 'Bu ilişkide “kelebekler” hâlâ var mı? (Dürüst ol)' },
  { d: 5, l: 3, a: 'romantizm', p: true, t: 'Evlilik teklifi anını kafanda kurdun mu hiç?' },
  { d: 5, l: 3, a: 'romantizm', p: true, t: 'Partnerin için yazılmış gibi hissettiğin bir şarkı var mı?' },

  // ---------- 6 · GÜNDELİK HAYAT BİLGİSİ ----------
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Partnerinin kahve/çay tercihini ezbere biliyor musun?' },
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Birlikte market alışverişi yapmak size keyifli geliyor mu?' },
  { d: 6, l: 1, a: 'emek', p: true, t: 'Bulaşık/ev işi paylaşımında üstüne düşeni yaptığını düşünüyor musun?' },
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Aynı dizide buluşabiliyor musunuz kavgasız?' },
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Partnerinin uyku düzenine saygı duyuyor musun?' },
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Yemek seçiminde “sen karar ver” kilitlenmesini kırabilen taraf sen misin?' },
  { d: 6, l: 1, a: 'sabir', p: true, t: 'Partnerinin dağınıklığına/aşırı düzenine tahammül edebiliyor musun?' },
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Birlikte hiçbir şey yapmadan oturmak bile keyifli mi?' },
  { d: 6, l: 1, a: 'emek', p: true, t: 'Partnerin yorgunken sen sofra kurar mısın?' },
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Klima/kombi sıcaklığında uzlaşabiliyor musunuz?' },
  { d: 6, l: 1, a: 'sabir', p: true, t: 'Partnerinin telefonla konuşma sesine katlanabiliyor musun?' },
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Pazar kahvaltısı ritüeliniz var mı?' },
  { d: 6, l: 1, a: 'emek', p: true, t: 'Partnerinin arabasına/odasına ondan habersiz çeki düzen verdiğin olur mu?' },
  { d: 6, l: 1, a: 'uyum', p: true, t: 'Müzik zevkleriniz yolculukta kavga çıkarmadan idare ediyor mu?' },
  { d: 6, l: 1, a: 'sabir', p: true, t: 'Partnerinin horlaması/uyku hareketleri dert olmaktan çıktı mı?' },
  { d: 6, l: 2, a: 'uyum', p: false, t: 'Ev işi paylaşımı yüzünden gerginlik yaşıyor musunuz?' },
  { d: 6, l: 2, a: 'sabir', p: false, t: 'Partnerinin bir günlük rutin alışkanlığı seni deli ediyor mu?' },
  { d: 6, l: 2, a: 'uyum', p: true, t: 'Birlikte yaşasanız ev kurallarında kolay anlaşır mısınız?' },
  { d: 6, l: 2, a: 'cesaret', p: true, t: 'Partnerinin yemeğini beğenmediğinde söyleyebilir misin?' },
  { d: 6, l: 2, a: 'uyum', p: false, t: 'Telefon kullanım süreniz aranızda sorun oluyor mu?' },
  { d: 6, l: 2, a: 'emek', p: true, t: 'Partnerinin unuttuğu işleri sessizce senin topladığın oluyor mu?' },
  { d: 6, l: 2, a: 'uyum', p: true, t: 'Tatil planlamasında görev dağılımınız adil mi?' },
  { d: 6, l: 2, a: 'sabir', p: false, t: 'Partnerinin geç kalma huyu seni çileden çıkarıyor mu?' },
  { d: 6, l: 2, a: 'uyum', p: true, t: 'Misafir ağırlarken uyumlu bir ekip misiniz?' },
  { d: 6, l: 2, a: 'emek', p: false, t: 'Ev içi görünmez emeğin (plan, hatırlatma, organizasyon) hep sende olduğunu düşünüyor musun?' },
  { d: 6, l: 2, a: 'uyum', p: true, t: 'Bütün gün beraber kalıp hiç sıkılmadığınız oluyor mu?' },
  { d: 6, l: 2, a: 'sabir', p: false, t: 'Partnerin araba kullanırken gerildiğin oluyor mu?' },
  { d: 6, l: 2, a: 'uyum', p: true, t: 'Alışkanlıklarınızın yüzde yetmişi uyumlu mu sence?' },
  { d: 6, l: 2, a: 'cesaret', p: true, t: 'Partnerinin giyimine dair fikrini dürüstçe söyleyebilir misin?' },
  { d: 6, l: 2, a: 'uyum', p: false, t: 'Hafta sonu planlarında sürekli taviz veren taraf olduğunu düşünüyor musun?' },
  { d: 6, l: 3, a: 'uyum', p: false, t: 'Birlikte yaşamanın ilişkinizi zorlayacağını düşünüyor musun?' },
  { d: 6, l: 3, a: 'cesaret', p: true, t: 'Partnerinin hijyen/düzen alışkanlıklarından gizlice rahatsız olduğun bir şey var mı? (Cesursan Evet)' },
  { d: 6, l: 3, a: 'sabir', p: false, t: 'Partnerinin bir huyu yüzünden “ben bununla yaşayamam” dediğin an oldu mu?' },
  { d: 6, l: 3, a: 'emek', p: false, t: 'Ev hayatında emeğinin görülmediğini hissediyor musun?' },
  { d: 6, l: 3, a: 'uyum', p: true, t: 'Partnerinle bir ay kesintisiz aynı odada çalışabilir misin?' },
  { d: 6, l: 3, a: 'cesaret', p: true, t: 'Partnerinin ailesindeki bir düzen/alışkanlık seni korkutuyor mu? (Cesursan Evet)' },
  { d: 6, l: 3, a: 'uyum', p: false, t: 'Gündelik sorumluluklar aşkınızı törpülüyor mu?' },
  { d: 6, l: 3, a: 'sabir', p: true, t: 'Partnerin işsiz kalsa günlük düzeni sen sırtlar mısın şikayetsiz?' },
  { d: 6, l: 3, a: 'uyum', p: true, t: 'Kirli çorap/diş macunu kapağı gibi klasik krizleri gülerek çözebilir misiniz?' },
  { d: 6, l: 3, a: 'emek', p: true, t: 'Partnerin hasta annesine/babasına bakmak zorunda kalsa ev yükünü tek başına taşır mısın?' },
  { d: 6, l: 3, a: 'uyum', p: false, t: 'Uyku saatleriniz uyumsuz diye ilişkiniz zarar görür mü sence?' },
  { d: 6, l: 3, a: 'cesaret', p: true, t: 'Partnerinin yemek yapamadığını yüzüne söyleyebilir misin?' },
  { d: 6, l: 3, a: 'uyum', p: true, t: 'Yirmi yıl sonra da aynı sofrada sohbetin biteceğini sanmıyor musun? (Bitmez=Evet)' },
  { d: 6, l: 3, a: 'sabir', p: false, t: 'Partnerinin sesli video izlemesi gibi küçük şeyler içinde birikiyor mu?' },
  { d: 6, l: 3, a: 'uyum', p: true, t: 'Ev dekorasyonunda tamamen ona teslim olabilir misin?' },

  // ---------- 7 · PARA VE EKONOMİ ----------
  { d: 7, l: 1, a: 'uyum', p: true, t: 'Hesabı kimin ödeyeceği konusunda rahat mısınız?' },
  { d: 7, l: 1, a: 'cesaret', p: true, t: 'Maaşını/kazancını partnerinle açıkça konuşabiliyor musun?' },
  { d: 7, l: 1, a: 'uyum', p: true, t: 'Para harcama tarzlarınız benzer mi?' },
  { d: 7, l: 1, a: 'emek', p: true, t: 'Partnerine bütçeni zorlayan bir hediye aldığın oldu mu?' },
  { d: 7, l: 1, a: 'uyum', p: true, t: 'Ortak kumbara/birikim fikri sana sıcak geliyor mu?' },
  { d: 7, l: 1, a: 'sabir', p: true, t: 'Partnerinin gereksiz bir alışverişine gülüp geçebilir misin?' },
  { d: 7, l: 1, a: 'cesaret', p: true, t: 'Borcun olsa partnerine söyler misin?' },
  { d: 7, l: 1, a: 'uyum', p: true, t: 'Tatil bütçesinde kolay anlaşır mısınız?' },
  { d: 7, l: 1, a: 'uyum', p: true, t: 'İkinizden biri cimri diğeri savurgan mı? (Hayır=dengedeyiz)' },
  { d: 7, l: 1, a: 'emek', p: true, t: 'Partnerinin parasını korumak için onu uyardığın olur mu?' },
  { d: 7, l: 1, a: 'uyum', p: true, t: 'Kampanya/indirim avcılığında aynı takımda mısınız?' },
  { d: 7, l: 1, a: 'cesaret', p: true, t: 'Aylık ne kadar harcadığını partnerin bilse rahatsız olmaz mısın?' },
  { d: 7, l: 1, a: 'uyum', p: true, t: 'Para konuşmak ilişkinizde tabu değil mi?' },
  { d: 7, l: 1, a: 'sabir', p: true, t: 'Partnerin sana pahalı gelen bir hobiye para harcasa saygı duyar mısın?' },
  { d: 7, l: 1, a: 'uyum', p: true, t: 'Düğün/kına gibi masraf kalemlerinde aynı kafada mısınız?' },
  { d: 7, l: 2, a: 'cesaret', p: true, t: 'Partnerinden gizli para biriktirir miydin? (Cesursan Evet)' },
  { d: 7, l: 2, a: 'uyum', p: false, t: 'Para yüzünden tartıştığınız oluyor mu?' },
  { d: 7, l: 2, a: 'emek', p: true, t: 'Partnerin zor durumdayken ona borç değil hibe verir miydin?' },
  { d: 7, l: 2, a: 'uyum', p: true, t: 'Evlilikte ortak hesap fikrine sıcak bakar mısın?' },
  { d: 7, l: 2, a: 'cesaret', p: true, t: 'Aldığın bir şeyin fiyatını partnerine düşük söylediğin oldu mu? (Cesursan Evet)' },
  { d: 7, l: 2, a: 'sabir', p: true, t: 'Partnerin işini bırakıp hayalinin peşinden gitse maddi yükü paylaşır mısın?' },
  { d: 7, l: 2, a: 'uyum', p: false, t: 'Birinizin ailesine para yardımı konusu gerginlik yaratır mı?' },
  { d: 7, l: 2, a: 'cesaret', p: true, t: 'Kazandığından fazla harcadığını kabul ediyor musun? (Cesursan Evet)' },
  { d: 7, l: 2, a: 'uyum', p: true, t: 'Kira mı ev kredisi mi tartışmasında anlaşabilir misiniz?' },
  { d: 7, l: 2, a: 'emek', p: true, t: 'Partnerinin eğitimi/kursu için birikiminden vazgeçer miydin?' },
  { d: 7, l: 2, a: 'uyum', p: false, t: 'Hediyeleşmede beklenti dengesizliği hissediyor musun?' },
  { d: 7, l: 2, a: 'sabir', p: true, t: 'Partnerin kumar değil ama riskli yatırım yapsa sakin kalır mısın?' },
  { d: 7, l: 2, a: 'cesaret', p: true, t: 'Ekonomik olarak partnerinden daha güçlü olmak seni rahatlatır mı? (Dürüst ol)' },
  { d: 7, l: 2, a: 'uyum', p: true, t: 'Bütçe uygulaması kullanıp harcamaları beraber takip etmeye var mısın?' },
  { d: 7, l: 2, a: 'emek', p: false, t: 'Ortak masraflarda hep senin cebinden çıktığını düşünüyor musun?' },
  { d: 7, l: 3, a: 'sadakat', p: true, t: 'Partnerin iflas etse ilişkin aynı kalır mıydı?' },
  { d: 7, l: 3, a: 'cesaret', p: true, t: 'Evlilik sözleşmesi (mal ayrılığı) ister miydin? (Cesursan Evet)' },
  { d: 7, l: 3, a: 'uyum', p: false, t: 'Gelir farkınız ilişkide güç dengesini bozuyor mu sence?' },
  { d: 7, l: 3, a: 'sadakat', p: false, t: 'Çok zengin biri çıksa karşına bu ilişkiyi sorgular mıydın?' },
  { d: 7, l: 3, a: 'emek', p: true, t: 'Partnerinin borcu için kredi çeker miydin?' },
  { d: 7, l: 3, a: 'cesaret', p: true, t: 'Paranı nasıl harcadığında tamamen özgür olmak istiyor musun? (Dürüst ol)' },
  { d: 7, l: 3, a: 'uyum', p: false, t: 'Biriniz çok kazanınca diğerinin eli işten soğur mu sence?' },
  { d: 7, l: 3, a: 'sadakat', p: true, t: 'Piyangodan büyük ikramiye çıksa ilk kararları partnerinle mi verirdin?' },
  { d: 7, l: 3, a: 'cesaret', p: true, t: 'Partnerinin maaşını tam olarak bilmiyor musun? (Bilmiyorum=Evet)' },
  { d: 7, l: 3, a: 'uyum', p: true, t: 'Maddi kriz dönemi ilişkinizi güçlendirir mi sence?' },
  { d: 7, l: 3, a: 'emek', p: false, t: 'Para harcama şeklin yüzünden kendini yargılanmış hissediyor musun?' },
  { d: 7, l: 3, a: 'sadakat', p: true, t: 'Mirasını partnerinle paylaşmakta tereddüt etmez miydin?' },
  { d: 7, l: 3, a: 'cesaret', p: true, t: 'Ekonomik bağımsızlık olmadan aşk yürümez diyenlerden misin?' },
  { d: 7, l: 3, a: 'uyum', p: false, t: 'Partnerinin ailesinin maddi beklentileri seni korkutuyor mu?' },
  { d: 7, l: 3, a: 'emek', p: true, t: 'Gerekirse iki iş çalışıp evi tek başına geçindirir miydin?' },

  // ---------- 8 · AİLE İLİŞKİLERİ ----------
  { d: 8, l: 1, a: 'uyum', p: true, t: 'Partnerinin ailesiyle görüşmek sana keyif veriyor mu?' },
  { d: 8, l: 1, a: 'uyum', p: true, t: 'Ailen partnerini seviyor mu sence?' },
  { d: 8, l: 1, a: 'emek', p: true, t: 'Partnerinin ailesine özel günlerde hediye almayı düşünür müsün?' },
  { d: 8, l: 1, a: 'uyum', p: true, t: 'Bayramlarda iki aileyi de dengeli ziyaret edebiliyor musunuz?' },
  { d: 8, l: 1, a: 'sabir', p: true, t: 'Partnerinin annesinin/babasının tavsiyelerini sabırla dinler misin?' },
  { d: 8, l: 1, a: 'uyum', p: true, t: 'Aile yemeklerinde kendini rahat hissediyor musun?' },
  { d: 8, l: 1, a: 'cesaret', p: true, t: 'Partnerini ailenle tanıştırırken heyecandan çok gurur mu duydun?' },
  { d: 8, l: 1, a: 'uyum', p: true, t: 'Kardeşleriyle/kuzenleriyle aran iyi mi?' },
  { d: 8, l: 1, a: 'emek', p: true, t: 'Partnerinin ailesinin bir işine koşturduğun oldu mu?' },
  { d: 8, l: 1, a: 'uyum', p: true, t: 'Aileler tanışsa güzel bir sofra olur mu sence?' },
  { d: 8, l: 1, a: 'sabir', p: true, t: 'Aile grubundaki mesajlara sabırla cevap verir misin?' },
  { d: 8, l: 1, a: 'uyum', p: true, t: 'Partnerinin ailesinin şakalarına içten gülebiliyor musun?' },
  { d: 8, l: 1, a: 'cesaret', p: true, t: 'Ailene partnerini savunduğun bir an oldu mu?' },
  { d: 8, l: 1, a: 'uyum', p: true, t: 'Anneler/Babalar Gününde partnerinin ailesini de arar mısın?' },
  { d: 8, l: 1, a: 'emek', p: true, t: 'Partnerinin ailesinin sevdiği yemeği öğrenmeye çalışır mısın?' },
  { d: 8, l: 2, a: 'cesaret', p: true, t: 'Ailen partnerin hakkında olumsuz konuşsa anında müdahale eder misin?' },
  { d: 8, l: 2, a: 'uyum', p: false, t: 'Partnerinin ailesinin ilişkinize fazla karıştığını düşünüyor musun?' },
  { d: 8, l: 2, a: 'sabir', p: true, t: 'Kayınvalide/kayınpeder klişelerinin sizde yaşanmayacağına inanıyor musun?' },
  { d: 8, l: 2, a: 'uyum', p: false, t: 'Aile ziyaretlerinin sıklığı konusunda anlaşmazlık yaşıyor musunuz?' },
  { d: 8, l: 2, a: 'cesaret', p: true, t: 'Partnerine ailesinin bir hatasını söyleyebilir misin?' },
  { d: 8, l: 2, a: 'uyum', p: true, t: 'Tatilde bir haftayı partnerinin ailesiyle geçirebilir misin?' },
  { d: 8, l: 2, a: 'sabir', p: false, t: 'Ailenin “ne zaman evleniyorsunuz” baskısı seni bunaltıyor mu?' },
  { d: 8, l: 2, a: 'uyum', p: true, t: 'Aileler arasında kültür farkı olsa yönetebilir misiniz?' },
  { d: 8, l: 2, a: 'cesaret', p: true, t: 'Partnerinin annesine/babasına itiraz edebilir misin gerektiğinde?' },
  { d: 8, l: 2, a: 'uyum', p: false, t: 'Partnerin ailesinin sözünü senin sözünden üstün tutuyor mu? (Dürüst ol)' },
  { d: 8, l: 2, a: 'emek', p: true, t: 'Partnerinin ailesinin bakıma ihtiyacı olsa evini açar mıydın?' },
  { d: 8, l: 2, a: 'sabir', p: true, t: 'Aile içi tartışmada tarafsız kalmayı becerebilir misin?' },
  { d: 8, l: 2, a: 'uyum', p: false, t: 'Ailelerin düğün/söz gibi konulardaki fikirleri sizi yoruyor mu?' },
  { d: 8, l: 2, a: 'cesaret', p: true, t: 'Aile sofrasında partnerinin elini tutmaktan çekinmez misin?' },
  { d: 8, l: 2, a: 'uyum', p: true, t: 'Kendi ailenin kusurlarını partnerine itiraf edebilir misin?' },
  { d: 8, l: 3, a: 'sadakat', p: true, t: 'Annen ile partnerin ciddi kavga etse partnerinin yanında durur muydun (haklıysa)?' },
  { d: 8, l: 3, a: 'cesaret', p: true, t: 'Ailenin partnerinde görmediği bir kusuru sen görüyor musun? (Cesursan Evet)' },
  { d: 8, l: 3, a: 'uyum', p: false, t: 'Partnerinin ailesi seni hâlâ tam kabullenmedi mi sence?' },
  { d: 8, l: 3, a: 'sadakat', p: true, t: 'Ailen bu ilişkiye tamamen karşı çıksa ilişkiyi sürdürür müydün?' },
  { d: 8, l: 3, a: 'sabir', p: false, t: 'Partnerinin ailesindeki bir kişiyle görüşmemeyi tercih eder miydin?' },
  { d: 8, l: 3, a: 'cesaret', p: true, t: 'Kayınvalidenle/kayınpederinle aynı evde yaşamayı reddeder miydin? (Dürüst ol)' },
  { d: 8, l: 3, a: 'uyum', p: false, t: 'Aile baskısının ilişkinizin yönünü değiştirdiğini düşünüyor musun?' },
  { d: 8, l: 3, a: 'sadakat', p: true, t: 'Partnerin, ailesiyle arasına mesafe koymanı istese saygı duyar mıydın?' },
  { d: 8, l: 3, a: 'cesaret', p: true, t: 'Partnerinin ailesinin bir sırrını biliyorsan ona söyler miydin?' },
  { d: 8, l: 3, a: 'uyum', p: false, t: 'İki ailenin dünya görüşü farkı ileride kriz çıkarır mı sence?' },
  { d: 8, l: 3, a: 'sabir', p: true, t: 'Aile davetinde sana yapılan bir laf dokundurmasını olay çıkarmadan yutabilir misin?' },
  { d: 8, l: 3, a: 'sadakat', p: true, t: 'Evlilikte “önce eşim sonra ailem” diyebilecek misin gerçekten?' },
  { d: 8, l: 3, a: 'cesaret', p: true, t: 'Partnerine “ailen bizi yoruyor” diyebilir misin gerekirse?' },
  { d: 8, l: 3, a: 'uyum', p: false, t: 'Çocuk büyütme tarzında ailelerin karışacağından endişeli misin?' },
  { d: 8, l: 3, a: 'emek', p: true, t: 'Partnerinin ailesi için kendi ailenden gizli fedakârlık yapar mıydın?' },

  // ---------- 9 · GELECEK PLANLAMA ----------
  { d: 9, l: 1, a: 'uyum', p: true, t: 'Beş yıl sonrasını hayal ettiğinde partnerin o tabloda var mı?' },
  { d: 9, l: 1, a: 'romantizm', p: true, t: 'Birlikte yaşlanma fikri sana huzur veriyor mu?' },
  { d: 9, l: 1, a: 'uyum', p: true, t: 'Hayat hedefleriniz aynı yöne bakıyor mu?' },
  { d: 9, l: 1, a: 'cesaret', p: true, t: 'Evlilik konusunu rahatça konuşabiliyor musunuz?' },
  { d: 9, l: 1, a: 'uyum', p: true, t: 'Nerede yaşayacağınız konusunda hayaliniz ortak mı?' },
  { d: 9, l: 1, a: 'emek', p: true, t: 'Ortak bir hayal için bugünden birikim/plan yapıyor musun?' },
  { d: 9, l: 1, a: 'uyum', p: true, t: 'Çocuk konusunda aynı fikirde olduğunuzu düşünüyor musun?' },
  { d: 9, l: 1, a: 'romantizm', p: true, t: 'Birlikte gitmek istediğin bir hayal rotanız var mı?' },
  { d: 9, l: 1, a: 'uyum', p: true, t: 'Emeklilikte bile birlikte sıkılmayacağınıza inanıyor musun?' },
  { d: 9, l: 1, a: 'cesaret', p: true, t: 'Gelecek planlarını partnerinle çekinmeden paylaşıyor musun?' },
  { d: 9, l: 1, a: 'uyum', p: true, t: 'Evcil hayvan kararında kolayca anlaşır mısınız?' },
  { d: 9, l: 1, a: 'emek', p: true, t: 'Partnerinin kariyer hayaline aktif destek veriyor musun?' },
  { d: 9, l: 1, a: 'romantizm', p: true, t: 'Düğün gününü hayal etmek sana keyif veriyor mu?' },
  { d: 9, l: 1, a: 'uyum', p: true, t: 'Yılbaşını nerede geçireceğiniz krizsiz çözülür mü sizde?' },
  { d: 9, l: 1, a: 'uyum', p: true, t: 'Gelecekte beraber bir işe/projeye girişebilir misiniz?' },
  { d: 9, l: 2, a: 'cesaret', p: true, t: 'Bu ilişkinin evlilikle biteceğine gerçekten inanıyor musun?' },
  { d: 9, l: 2, a: 'uyum', p: false, t: 'Kariyer ve şehir tercihi çakışırsa kriz çıkar mı sizde?' },
  { d: 9, l: 2, a: 'uyum', p: true, t: 'Çocuğun eğitimi/dini/dili gibi konularda uzlaşabilir misiniz?' },
  { d: 9, l: 2, a: 'cesaret', p: true, t: 'Partnerinin ebeveynlik tarzının nasıl olacağını öngörebiliyor musun?' },
  { d: 9, l: 2, a: 'emek', p: true, t: 'Ortak gelecek için bireysel bir hayalinden vazgeçebilir misin?' },
  { d: 9, l: 2, a: 'uyum', p: false, t: 'Zaman planlarınız (kaçta evlilik, kaçta çocuk) uyuşmuyor mu?' },
  { d: 9, l: 2, a: 'cesaret', p: true, t: 'Partnerin yurt dışına taşınmak istese ciddi ciddi düşünür müsün?' },
  { d: 9, l: 2, a: 'uyum', p: true, t: 'Maddi hedefleriniz (ev, araba, birikim) örtüşüyor mu?' },
  { d: 9, l: 2, a: 'romantizm', p: true, t: 'On yıl sonra da el ele yürüdüğünüzü hayal edebiliyor musun?' },
  { d: 9, l: 2, a: 'cesaret', p: true, t: 'İlişkinin geleceğiyle ilgili bir korkunu partnerinden sakladın mı? (Cesursan Evet)' },
  { d: 9, l: 2, a: 'uyum', p: false, t: 'Aileler geleceğinizle ilgili planlara fazla mı dahil?' },
  { d: 9, l: 2, a: 'emek', p: true, t: 'Partnerin okula dönmek istese evi tek maaşla çevirmeyi kabul eder misin?' },
  { d: 9, l: 2, a: 'uyum', p: true, t: 'Tatil-yaşam dengesi hayalleriniz (şehir/köy, yurtiçi/yurtdışı) uyumlu mu?' },
  { d: 9, l: 2, a: 'cesaret', p: true, t: 'Evliliğe dair beklentilerinizi (rollere kadar) hiç açık açık konuştunuz mu?' },
  { d: 9, l: 2, a: 'uyum', p: true, t: 'Kriz anında (işsizlik, hastalık) planınız belli mi?' },
  { d: 9, l: 3, a: 'cesaret', p: true, t: 'Bu ilişki beş yıl sonra hâlâ sürüyor olacak — iddiaya girer misin?' },
  { d: 9, l: 3, a: 'uyum', p: false, t: 'Çocuk istememe/isteme konusunda derinlerde fikir ayrılığınız var mı?' },
  { d: 9, l: 3, a: 'sadakat', p: true, t: 'Partnerin ağır hastalansa geleceğini yine de onunla kurar mıydın?' },
  { d: 9, l: 3, a: 'cesaret', p: true, t: 'Evlilik sana özgürlük kaybı gibi mi geliyor? (Dürüst ol)' },
  { d: 9, l: 3, a: 'uyum', p: false, t: 'Partnerinin hayat temposuyla kendi temponun uzun vadede çatışacağını düşünüyor musun?' },
  { d: 9, l: 3, a: 'emek', p: true, t: 'Partnerinin hayali için emekliliğini on yıl erteler miydin?' },
  { d: 9, l: 3, a: 'cesaret', p: true, t: 'İlişkiniz bitse hayat planın tamamen çöker miydi? (Dürüst ol)' },
  { d: 9, l: 3, a: 'uyum', p: true, t: 'Zor bir hamilelik/ebeveynlik döneminde güçlü kalacağınıza inanıyor musun?' },
  { d: 9, l: 3, a: 'sadakat', p: true, t: 'Gelecekte daha iyi biriyle tanışma ihtimali seni hiç mi cezbetmiyor?' },
  { d: 9, l: 3, a: 'cesaret', p: true, t: 'Partnerine hiç söylemediğin bir gelecek hayalin var mı? (Cesursan Evet)' },
  { d: 9, l: 3, a: 'uyum', p: false, t: 'Onun ailesiyle aynı mahallede yaşama ihtimali seni terletiyor mu?' },
  { d: 9, l: 3, a: 'emek', p: true, t: 'Gerekirse çocuk için kariyerine uzun ara verir miydin?' },
  { d: 9, l: 3, a: 'romantizm', p: true, t: 'Seksen yaşında da bu insanla kahvaltı etmek sana güzel mi geliyor?' },
  { d: 9, l: 3, a: 'cesaret', p: true, t: 'Evlilik sözleşmenizde en çok hangi maddenin tartışma çıkaracağını biliyor musun?' },
  { d: 9, l: 3, a: 'uyum', p: true, t: 'İkinizin de değişeceğini kabul edip yine de söz verebilir misin?' },

  // ---------- 10 · GEÇMİŞ TARİHİ ----------
  { d: 10, l: 1, a: 'cesaret', p: true, t: 'Geçmiş ilişkilerinden partnerine rahatça bahsedebilir misin?' },
  { d: 10, l: 1, a: 'sabir', p: true, t: 'Partnerinin geçmişini merak etmeden kabullenebiliyor musun?' },
  { d: 10, l: 1, a: 'uyum', p: true, t: 'Tanışma anınızı ikiniz de aynı şekilde mi hatırlıyorsunuz sence?' },
  { d: 10, l: 1, a: 'cesaret', p: true, t: 'Çocukluğunun utanç verici hikayelerini partnerine anlattın mı?' },
  { d: 10, l: 1, a: 'sabir', p: true, t: 'Partnerinin eski fotoğraflarına gülüp geçebiliyor musun?' },
  { d: 10, l: 1, a: 'romantizm', p: true, t: 'İlk mesajlaşmalarınızı arada açıp okuyor musun?' },
  { d: 10, l: 1, a: 'cesaret', p: true, t: 'Ailenle ilgili zor bir anını partnerinle paylaştın mı?' },
  { d: 10, l: 1, a: 'sabir', p: true, t: 'Geçmişte kalan konuları geçmişte bırakabiliyor musun?' },
  { d: 10, l: 1, a: 'uyum', p: true, t: 'İkinizin de geçmişi bugününüzü zenginleştiriyor mu sence?' },
  { d: 10, l: 1, a: 'cesaret', p: true, t: 'En büyük pişmanlığını partnerin biliyor mu?' },
  { d: 10, l: 1, a: 'romantizm', p: true, t: 'İlk buluşmanızda ne giydiğini hatırlıyor musun?' },
  { d: 10, l: 1, a: 'sabir', p: true, t: 'Partnerin eski bir anısını anlatırken keyifle dinler misin?' },
  { d: 10, l: 1, a: 'cesaret', p: true, t: 'Gençliğindeki halinle şimdiki halin arasındaki farkı anlatabilir misin?' },
  { d: 10, l: 1, a: 'uyum', p: true, t: 'Geçmiş zorluklarının seni bu ilişkiye hazırladığını düşünüyor musun?' },
  { d: 10, l: 1, a: 'romantizm', p: true, t: 'Tanışmadan önceki hayatını “eksik” olarak tarif eder misin?' },
  { d: 10, l: 2, a: 'cesaret', p: true, t: 'Eski ilişkinden bu ilişkiye taşıdığın bir korku var mı? (Cesursan Evet)' },
  { d: 10, l: 2, a: 'sabir', p: true, t: 'Partnerinin eski sevgilisinin adını duyunca yüzün düşmüyor mu?' },
  { d: 10, l: 2, a: 'cesaret', p: true, t: 'Geçmişte kalp kırdığını kabul ediyor musun?' },
  { d: 10, l: 2, a: 'sabir', p: false, t: 'Partnerinin geçmişiyle ilgili detayları sorguladığın oluyor mu?' },
  { d: 10, l: 2, a: 'cesaret', p: true, t: 'İlk aşkını partnerine dürüstçe anlattın mı?' },
  { d: 10, l: 2, a: 'uyum', p: false, t: 'Geçmiş konuları açıldığında kavga çıkma riski var mı sizde?' },
  { d: 10, l: 2, a: 'cesaret', p: true, t: 'Gençlikte yaptığın en çılgın şeyi partnerin biliyor mu?' },
  { d: 10, l: 2, a: 'sabir', p: true, t: 'Partnerinin “o dönem farklı biriydim” açıklamasını kabul eder misin?' },
  { d: 10, l: 2, a: 'cesaret', p: true, t: 'Terapiye gitmişliğin/gitme ihtiyacın olduğunu partnerinle konuştun mu?' },
  { d: 10, l: 2, a: 'sabir', p: false, t: 'Eski sevgilinle kıyaslama yaptığın oluyor mu için için?' },
  { d: 10, l: 2, a: 'cesaret', p: true, t: 'Ailenin geçmişteki bir hatasını partnerine itiraf edebildin mi?' },
  { d: 10, l: 2, a: 'uyum', p: true, t: 'İkinizin geçmiş defterleri tamamen kapandı mı sence?' },
  { d: 10, l: 2, a: 'sabir', p: true, t: 'Partnerinin geçmiş “çılgın dönemine” takılmadan bakabiliyor musun?' },
  { d: 10, l: 2, a: 'cesaret', p: true, t: 'En derin sırrının yüzde kaçını partnerin biliyor? (Bar ile göster)' },
  { d: 10, l: 2, a: 'sabir', p: false, t: 'Geçmişte yaşadığın bir travmanın bu ilişkiye gölge düşürdüğünü hissediyor musun?' },
  { d: 10, l: 3, a: 'cesaret', p: true, t: 'Partnerinin bilmediği ve öğrense üzüleceği bir geçmişin var mı? (Cesursan Evet)' },
  { d: 10, l: 3, a: 'sabir', p: true, t: 'Partnerin geçmişte birinden çok etkilenmiş olsa bile bugüne güvenir misin?' },
  { d: 10, l: 3, a: 'cesaret', p: true, t: 'Eski sevgilinle yaşadığın en güzel anıyı partnerine anlatabilir misin?' },
  { d: 10, l: 3, a: 'sadakat', p: false, t: 'Geçmişteki biriyle “kapanmamış hesap” hissin var mı hâlâ?' },
  { d: 10, l: 3, a: 'cesaret', p: true, t: 'İlişkinizin başında söylediğin bir yalanı şimdi itiraf edebilir misin?' },
  { d: 10, l: 3, a: 'sabir', p: false, t: 'Partnerinin geçmişini bilmek yerine hiç bilmemeyi mi tercih ederdin?' },
  { d: 10, l: 3, a: 'cesaret', p: true, t: 'Hayatının en dip anını partnerine bütün çıplaklığıyla anlattın mı?' },
  { d: 10, l: 3, a: 'sadakat', p: true, t: 'Eski sevgilin “geri dön” dese bir saniye bile düşünmez misin?' },
  { d: 10, l: 3, a: 'cesaret', p: true, t: 'Partnerinin geçmişinde seni hâlâ rahatsız eden net bir olay var mı? (Cesursan Evet)' },
  { d: 10, l: 3, a: 'sabir', p: true, t: 'Partnerin sana geçmişiyle ilgili acı bir itirafta bulunsa sarılır mısın önce?' },
  { d: 10, l: 3, a: 'cesaret', p: true, t: 'Bu ilişkide “keşke baştan dürüst olsaydım” dediğin bir konu var mı?' },
  { d: 10, l: 3, a: 'uyum', p: false, t: 'Geçmiş yaraların bu ilişkinin şeklini belirlediğini düşünüyor musun?' },
  { d: 10, l: 3, a: 'sadakat', p: true, t: 'Partnerinin geçmişindeki herkesle tokalaşabilir misin içten içe?' },
  { d: 10, l: 3, a: 'cesaret', p: true, t: 'Kendi geçmişinden en çok neyi silmek isterdin — partnerin bunu biliyor mu?' },
  { d: 10, l: 3, a: 'sabir', p: true, t: 'Geçmişi tamamen affetmek mümkün mü sence?' },

  // ---------- 11 · YASAK BÖLGE (18+) ----------
  { d: 11, l: 2, a: 'romantizm', p: true, t: 'Fiziksel yakınlığınızın sıklığından memnun musun?' },
  { d: 11, l: 2, a: 'cesaret', p: true, t: 'Yatakta ne istediğini partnerine açıkça söyleyebiliyor musun?' },
  { d: 11, l: 2, a: 'romantizm', p: true, t: 'İlk öpüşmenizi bugün gibi hatırlıyor musun?' },
  { d: 11, l: 2, a: 'cesaret', p: true, t: 'Fantezilerini partnerinle paylaşmaktan çekinmiyor musun?' },
  { d: 11, l: 2, a: 'uyum', p: true, t: 'Tempolarınızın uyumlu olduğunu düşünüyor musun?' },
  { d: 11, l: 2, a: 'cesaret', p: true, t: 'Beğenmediğin bir şeyi kırmadan söyleyebiliyor musun?' },
  { d: 11, l: 2, a: 'romantizm', p: true, t: 'Öpüşme sizde hâlâ heyecan verici mi?' },
  { d: 11, l: 2, a: 'uyum', p: true, t: 'Bu konularda şakalaşabilen bir çift misiniz?' },
  { d: 11, l: 2, a: 'cesaret', p: true, t: 'İlk gecenizi düşününce gülümsüyor musun?' },
  { d: 11, l: 2, a: 'romantizm', p: true, t: 'Partnerinin sana dokunuşu hâlâ elektrik veriyor mu?' },
  { d: 11, l: 2, a: 'uyum', p: true, t: 'Sınırlarınızı hiç konuşmadan da anlaşabiliyor musunuz?' },
  { d: 11, l: 2, a: 'cesaret', p: true, t: 'Bu dersin sorularını partnerinin yanında sesli okuyabilir misin?' },
  { d: 11, l: 3, a: 'cesaret', p: true, t: 'Denemek isteyip de hiç söyleyemediğin bir şey var mı? (Cesursan Evet)' },
  { d: 11, l: 3, a: 'cesaret', p: true, t: 'Yatakta bir şeyi idare ettiğin (rol yaptığın) oldu mu? (Cesursan Evet)' },
  { d: 11, l: 3, a: 'uyum', p: false, t: 'İstek dengesizliği yaşadığınız dönemler oluyor mu?' },
  { d: 11, l: 3, a: 'cesaret', p: true, t: 'Partnerinin bir fantezisini reddettin mi hiç?' },
  { d: 11, l: 3, a: 'romantizm', p: true, t: 'En unutulmaz anınızın hangisi olduğunda ikiniz de hemfikir misiniz sence?' },
  { d: 11, l: 3, a: 'cesaret', p: true, t: 'Bu konuda partnerine verdiğin puan 80 üstü mü? (Bar ile göster)' },
  { d: 11, l: 3, a: 'uyum', p: true, t: 'Yorgunluk/stres dönemlerinde bile yakınlığı koruyabiliyor musunuz?' },
  { d: 11, l: 3, a: 'cesaret', p: true, t: 'İlk birlikteliğinizde çok gergin olduğunu itiraf eder misin?' },
  { d: 11, l: 3, a: 'romantizm', p: true, t: 'Spontane anlar mı planlı romantik geceler mi — spontane diyorsan Evet?' },
  { d: 11, l: 3, a: 'cesaret', p: true, t: 'Bu dersten alacağın notu şimdiden tahmin edebiliyor musun?' },
]
